#!/bin/sh
"exec" "`dirname $0`/venv/bin/python" "$0" "$@"

from passlib.hash import pbkdf2_sha256
import sqlite3
import threading
import os.path as os_path
import yaml
import argparse

# The project root of the alfons project
PATH = os_path.dirname(os_path.abspath(__file__)) + "/Alfons/"

class LockableSqliteConnection(object):
	def __init__(self, dburi):
		self.lock = threading.Lock()
		self.connection = sqlite3.connect(dburi, check_same_thread=False)
		self.cursor = self.connection.cursor()
	def __enter__(self):
		self.lock.acquire()
		self.cursor = self.connection.cursor()
		return self
	def __exit__(self, type, value, traceback):
		self.lock.release()
		self.connection.commit()
		if self.cursor is not None:
			self.cursor.close()
			self.cursor = None

# These two functions are the brightest things I've coded all my life
def setupSubparsers(parser, T):
	if "subparsers" in T:
		sub = parser.add_subparsers(dest=T["name"])
		for t in T["subparsers"]:
			tParser = sub.add_parser(t["name"])
			if "arguments" in t:
				for a in t["arguments"]:
					name = a["name"]
					b = a.copy()
					del b["name"]
					tParser.add_argument(name, **b)
			setupSubparsers(tParser, t)

def runAction(T, p=None, args=None):
	if args == None and not p == None: args = p.parse_args()
	for t in T["subparsers"]:
		if t["name"] == getattr(args, T["name"]):
			if "cmd" in t:
				a = vars(args)
				b = [a[k] for k in a if k in [x["name"] for x in t["arguments"]]] if "arguments" in t else []
				return t["cmd"](*b)
			elif "subparsers" in t:
				return runAction(t, args=args)
	if not p == None: p.print_help()

def easyArguments(T):
	parser = argparse.ArgumentParser()
	setupSubparsers(parser, T)
	return runAction(T, p=parser)

def newPassword(username, password):
	with db:
		fetch = db.cursor.execute("SELECT password FROM users WHERE username = ?", [username]).fetchone()
		if fetch != None and len(fetch) == 1:
			hashed = pbkdf2_sha256.hash(password)

			db.cursor.execute("UPDATE users SET password = ? WHERE username = ?", [hashed, username])
			return "Password updated"
		else:
			return "Username '{}' not found".format(username)

def verifyPassword(username, password):
	with db:
		fetch = db.cursor.execute("SELECT password FROM users WHERE username = ?", [username]).fetchone()
		if fetch != None and len(fetch) == 1:
			if pbkdf2_sha256.verify(password, fetch[0]):
				return "Password matches!"
			else:
				return "Password doesn't match that for user {}".format(username)
		else:
			return "Username '{}' not found".format(username)

argTree = {
	"name": "parser",
	"description": "hejsan",
	"subparsers": [
		{
			"name": "newpass",
			"cmd": newPassword,
			"arguments": [
				{
					"name": "username"
				},
				{
					"name": "password"
				}
			]
		},
		{
			"name": "verify",
			"cmd": verifyPassword,
			"arguments": [
				{
					"name": "username"
				},
				{
					"name": "password"
				}
			]
		}
	]
}

def main():
	global parser
	with open(PATH + "config/alfons.yaml") as f:
		config = yaml.safe_load(f)

	if "data_path" not in config:
		return "No data path in config file"

	# If the data path doesn't start with a / it's a path relative to the project root
	if not config["data_path"].startswith("/"):
		config["data_path"] = PATH + config["data_path"]

	global db
	db = LockableSqliteConnection(config["data_path"] + "Alfons.db")

	if easyArguments(argTree) is None:
		return ""

if __name__ == "__main__":
	#print(main())
	main()
